import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import { Magnetometer } from 'expo-sensors';
import Ionicons from '@react-native-vector-icons/ionicons';
import { useLocalSearchParams } from 'expo-router';
import { obtenerLugarPorId } from '@/src/servicios/lugares';
import { Coordenadas, Lugar } from '@/src/tipos';
import { distanciaKm, formatearDistancia, rumboGrados } from '@/src/utilidades/distancia';
import { useTema } from '@/src/contexto/TemaContext';
export default function Orientar(){const{id}=useLocalSearchParams<{id:string}>();const{colores}=useTema();const[lugar,setLugar]=useState<Lugar|null>(null);const[pos,setPos]=useState<Coordenadas|null>(null);const[heading,setHeading]=useState(0);const[error,setError]=useState('');useEffect(()=>{if(id)obtenerLugarPorId(id).then(r=>{'datos'in r&&setLugar(r.datos)});(async()=>{const p=await Location.requestForegroundPermissionsAsync();if(!p.granted){setError('Sin ubicación no podemos calcular la dirección. El resto de la app sigue funcionando.');return;}const u=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setPos({latitud:u.coords.latitude,longitud:u.coords.longitude});})();Magnetometer.setUpdateInterval(250);const sub=Magnetometer.addListener(({x,y})=>{let h=Math.atan2(y,x)*180/Math.PI;h=(h+360)%360;setHeading(h)});return()=>sub.remove();},[id]);const rumbo=useMemo(()=>pos&&lugar?rumboGrados(pos,lugar.coordenadas):0,[pos,lugar]);const rot=(rumbo-heading+360)%360;if(error)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Ionicons name="location-outline" size={44} color={colores.primario}/><Text style={[s.title,{color:colores.tinta}]}>Ubicación desactivada</Text><Text style={[s.text,{color:colores.secundario}]}>{error}</Text></View>;return <View style={[s.center,{backgroundColor:colores.fondo}]}><Text style={[s.kicker,{color:colores.primario}]}>ORIENTACIÓN</Text><Text style={[s.title,{color:colores.tinta}]}>{lugar?.nombre??'Cargando…'}</Text><View style={[s.compass,{borderColor:colores.borde,backgroundColor:colores.superficie}]}><Text style={[s.north,{color:colores.secundario}]}>N</Text><View style={{transform:[{rotate:`${rot}deg`}],alignItems:'center'}}><Ionicons name="navigate" size={100} color={colores.primario}/></View></View>{pos&&lugar?<Text style={[s.distance,{color:colores.tinta}]}>{formatearDistancia(distanciaKm(pos,lugar.coordenadas))}</Text>:null}<Text style={[s.text,{color:colores.secundario}]}>La flecha combina tu ubicación con el magnetómetro del teléfono. Movelo en forma de “8” si la brújula necesita calibración.</Text></View>}
const s=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:26},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.4},title:{fontSize:26,fontWeight:'900',textAlign:'center',marginTop:7},compass:{width:245,height:245,borderRadius:999,borderWidth:1,alignItems:'center',justifyContent:'center',marginVertical:26},north:{position:'absolute',top:12,fontWeight:'900'},distance:{fontSize:22,fontWeight:'900'},text:{textAlign:'center',lineHeight:21,marginTop:10}});
