import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@react-native-vector-icons/ionicons';
import { Evento } from '@/src/tipos';
import { obtenerEventoPorId } from '@/src/servicios/eventos';
import { obtenerLugarPorId } from '@/src/servicios/lugares';
import { estaEventoGuardado, guardarEvento, quitarEvento } from '@/src/servicios/eventosGuardados';
import { useTema } from '@/src/contexto/TemaContext';
import { useSesion } from '@/src/contexto/SesionContext';
import { fechaEvento, pesos } from '@/src/utilidades/formato';
import { EstadoContenido } from '@/src/componentes/EstadoContenido';
export default function DetalleEvento(){const{id}=useLocalSearchParams<{id:string}>();const{colores}=useTema();const{usuario}=useSesion();const[e,setE]=useState<Evento|null>(null);const[lugar,setLugar]=useState<string|null>(null);const[guardado,setGuardado]=useState(false);const[cargando,setCargando]=useState(true);useEffect(()=>{if(!id)return;(async()=>{const r=await obtenerEventoPorId(id);if('datos'in r){setE(r.datos);if(r.datos.lugarId){const l=await obtenerLugarPorId(r.datos.lugarId);if('datos'in l)setLugar(l.datos.nombre);}if(usuario)setGuardado(await estaEventoGuardado(usuario.id,id));}setCargando(false)})()},[id,usuario?.id]);if(cargando)return <View style={[s.center,{backgroundColor:colores.fondo}]}><EstadoContenido tipo="cargando"/></View>;if(!e)return <View style={[s.center,{backgroundColor:colores.fondo}]}><EstadoContenido tipo="error" mensaje="Evento no encontrado."/></View>;
 const toggle=async()=>{if(!usuario){router.push('/(tabs)/cuenta');return;}if(guardado){await quitarEvento(usuario.id,e.id);setGuardado(false);}else{try{await guardarEvento(usuario.id,e);setGuardado(true);Alert.alert('Guardado','Te avisaremos antes de que empiece.');}catch(err){Alert.alert('No se pudo guardar',err instanceof Error?err.message:'Error')}}};
 return <ScrollView style={{flex:1,backgroundColor:colores.fondo}} contentContainerStyle={{paddingBottom:30}}>{e.imagenUrl?<Image source={{uri:e.imagenUrl}} style={s.hero}/>:null}<View style={s.content}><Text style={[s.date,{color:colores.primario}]}>{fechaEvento(e.inicio)}</Text><Text style={[s.title,{color:colores.tinta}]}>{e.titulo}</Text><Text style={[s.state,{color:e.estado==='programado'?colores.exito:colores.peligro}]}>{e.estado.toUpperCase()}</Text><Text style={[s.desc,{color:colores.tinta}]}>{e.descripcion}</Text><View style={[s.card,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><Text style={[s.label,{color:colores.secundario}]}>Lugar</Text><Text style={[s.value,{color:colores.tinta}]}>{lugar??e.direccionLibre??'A confirmar'}</Text><Text style={[s.label,{color:colores.secundario}]}>Precio</Text><Text style={[s.value,{color:colores.tinta}]}>{pesos(e.precio)}</Text></View><Pressable onPress={toggle} style={[s.btn,{backgroundColor:guardado?colores.primarioSuave:colores.primario}]}><Ionicons name={guardado?'bookmark':'bookmark-outline'} size={20} color={guardado?colores.primario:'white'}/><Text style={{color:guardado?colores.primario:'white',fontWeight:'900'}}>{guardado?'Quitar de guardados':'Guardar y avisarme'}</Text></Pressable>{e.lugarId?<Pressable onPress={()=>router.push({pathname:'/lugar/[id]',params:{id:e.lugarId}})} style={s.link}><Text style={{color:colores.primario,fontWeight:'900'}}>Ver lugar asociado</Text><Ionicons name="chevron-forward" size={18} color={colores.primario}/></Pressable>:null}</View></ScrollView>}
const s=StyleSheet.create({center:{flex:1,justifyContent:'center',padding:20},hero:{width:'100%',height:230},content:{padding:20},date:{fontWeight:'900',textTransform:'capitalize'},title:{fontSize:30,lineHeight:35,fontWeight:'900',marginTop:6},state:{fontSize:12,fontWeight:'900',marginTop:8},desc:{fontSize:16,lineHeight:25,marginTop:16},card:{borderWidth:1,borderRadius:18,padding:16,marginTop:18,gap:3},label:{fontSize:11,fontWeight:'800',marginTop:7},value:{fontSize:16,fontWeight:'900'},btn:{marginTop:18,padding:15,borderRadius:15,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},link:{marginTop:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:4}});
