import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions, BarcodeScanningResult } from 'expo-camera';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import Ionicons from '@react-native-vector-icons/ionicons';
import { obtenerLugarPorQr } from '@/src/servicios/lugares';
import { registrarVisita } from '@/src/servicios/visitas';
import { useSesion } from '@/src/contexto/SesionContext';
import { useTema } from '@/src/contexto/TemaContext';
export default function Escanear(){const{usuario}=useSesion();const{colores}=useTema();const[permiso,pedirPermiso]=useCameraPermissions();const[procesando,setProcesando]=useState(false);if(!usuario)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Ionicons name="lock-closed-outline" size={36} color={colores.primario}/><Text style={[s.title,{color:colores.tinta}]}>Ingresá para registrar visitas</Text><Pressable style={[s.btn,{backgroundColor:colores.primario}]} onPress={()=>router.replace('/(tabs)/cuenta')}><Text style={s.btnText}>Ir a mi cuenta</Text></Pressable></View>;if(!permiso)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Text style={{color:colores.secundario}}>Consultando permiso de cámara…</Text></View>;if(!permiso.granted)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Ionicons name="camera-outline" size={40} color={colores.primario}/><Text style={[s.title,{color:colores.tinta}]}>Necesitamos la cámara</Text><Text style={[s.text,{color:colores.secundario}]}>Se usa sólo para leer los QR oficiales de los lugares.</Text><Pressable style={[s.btn,{backgroundColor:colores.primario}]} onPress={pedirPermiso}><Text style={s.btnText}>Permitir cámara</Text></Pressable></View>;
 const leer=async(result:BarcodeScanningResult)=>{if(procesando)return;setProcesando(true);const r=await obtenerLugarPorQr(result.data);if('error'in r){await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);Alert.alert('QR no válido',r.error.mensaje,[{text:'Intentar de nuevo',onPress:()=>setProcesando(false)}]);return;}await registrarVisita(usuario.id,r.datos.id,'qr');await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Visita registrada',`Guardamos tu visita a ${r.datos.nombre}.`,[{text:'Ver recorrido',onPress:()=>router.replace('/(tabs)/recorrido')}]);};
 return <View style={s.root}><CameraView style={StyleSheet.absoluteFill} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={procesando?undefined:leer}/><View style={s.overlay}><View style={s.frame}><View style={s.corner}/></View><Text style={s.tip}>Apuntá al QR oficial del cartel</Text></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'black'},overlay:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(0,0,0,.22)'},frame:{width:260,height:260,borderWidth:3,borderColor:'white',borderRadius:28},corner:{width:26,height:26,borderTopWidth:5,borderLeftWidth:5,borderColor:'#6FD0B2',borderTopLeftRadius:8,margin:14},tip:{marginTop:22,color:'white',fontWeight:'900',fontSize:16,backgroundColor:'rgba(0,0,0,.6)',paddingHorizontal:15,paddingVertical:10,borderRadius:12},center:{flex:1,justifyContent:'center',alignItems:'center',padding:28},title:{fontSize:24,fontWeight:'900',textAlign:'center',marginTop:12},text:{textAlign:'center',marginVertical:12,lineHeight:20},btn:{paddingHorizontal:18,paddingVertical:14,borderRadius:14,marginTop:12},btnText:{color:'white',fontWeight:'900'}});
