import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import * as ImagePicker from 'expo-image-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@react-native-vector-icons/ionicons';
import { obtenerLugares } from '@/src/servicios/lugares';
import { registrarVisita, validarCercania } from '@/src/servicios/visitas';
import { Lugar, OrigenVisita } from '@/src/tipos';
import { useSesion } from '@/src/contexto/SesionContext';
import { useTema } from '@/src/contexto/TemaContext';
export default function RegistrarVisita(){const params=useLocalSearchParams<{lugarId?:string;origen?:string}>();const{usuario}=useSesion();const{colores}=useTema();const[lugares,setLugares]=useState<Lugar[]>([]);const[seleccion,setSeleccion]=useState<string|null>(params.lugarId??null);const[nota,setNota]=useState('');const[foto,setFoto]=useState<string|null>(null);const[guardando,setGuardando]=useState(false);const origen:OrigenVisita=params.origen==='gps'?'gps':'manual';useEffect(()=>{obtenerLugares().then(r=>{'datos'in r&&setLugares(r.datos)})},[]);if(!usuario)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Text style={[s.h1,{color:colores.tinta}]}>Ingresá para registrar visitas</Text><Pressable style={[s.btn,{backgroundColor:colores.primario}]} onPress={()=>router.replace('/(tabs)/cuenta')}><Text style={s.btnText}>Ir a mi cuenta</Text></Pressable></View>;
 const camara=async()=>{const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Cámara desactivada','Podés continuar sin foto o habilitar el permiso desde Ajustes.');return;}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],allowsEditing:true,quality:.8});if(!r.canceled)setFoto(r.assets[0].uri)};
 const galeria=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.8});if(!r.canceled)setFoto(r.assets[0].uri)};
 const guardar=async()=>{if(!seleccion){Alert.alert('Elegí un lugar');return;}setGuardando(true);try{if(origen==='gps'){const v=await validarCercania(seleccion);if(!v.ok){Alert.alert('No pudimos validar cercanía',v.mensaje);setGuardando(false);return;}}await registrarVisita(usuario.id,seleccion,origen,nota,foto);await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);router.replace('/(tabs)/recorrido');}catch(e){Alert.alert('No se pudo guardar',e instanceof Error?e.message:'Error inesperado');}finally{setGuardando(false)}};
 return <ScrollView style={{flex:1,backgroundColor:colores.fondo}} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={[s.h1,{color:colores.tinta}]}>{origen==='gps'?'Validar visita por cercanía':'Registrar visita manual'}</Text><Text style={[s.text,{color:colores.secundario}]}>{origen==='gps'?'Al guardar comprobaremos que estés cerca del lugar. Si negás ubicación, podés usar el registro manual.':'Elegí el lugar, agregá una foto y una nota si querés.'}</Text><Text style={[s.label,{color:colores.tinta}]}>Lugar</Text>{lugares.map(l=><Pressable key={l.id} onPress={()=>setSeleccion(l.id)} style={[s.item,{backgroundColor:seleccion===l.id?colores.primario:colores.superficie,borderColor:seleccion===l.id?colores.primario:colores.borde}]}><Text style={{fontWeight:'900',color:seleccion===l.id?'white':colores.tinta}}>{l.nombre}</Text></Pressable>)}<Text style={[s.label,{color:colores.tinta,marginTop:14}]}>Foto de la visita</Text><View style={s.photoActions}><Pressable onPress={camara} style={[s.photoBtn,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><Ionicons name="camera-outline" size={21} color={colores.primario}/><Text style={{color:colores.tinta,fontWeight:'900'}}>Sacar foto</Text></Pressable><Pressable onPress={galeria} style={[s.photoBtn,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><Ionicons name="images-outline" size={21} color={colores.primario}/><Text style={{color:colores.tinta,fontWeight:'900'}}>Galería</Text></Pressable></View>{foto?<View><Image source={{uri:foto}} style={s.photo}/><Pressable onPress={()=>setFoto(null)}><Text style={{color:colores.peligro,fontWeight:'900',textAlign:'center',marginTop:7}}>Quitar foto</Text></Pressable></View>:null}<TextInput style={[s.input,{backgroundColor:colores.superficie,borderColor:colores.borde,color:colores.tinta}]} value={nota} onChangeText={setNota} placeholder="Nota corta opcional" placeholderTextColor={colores.secundario} multiline maxLength={240}/><Pressable disabled={guardando} style={[s.btn,{backgroundColor:colores.primario,opacity:guardando?0.7:1}]} onPress={guardar}><Text style={s.btnText}>{guardando?'Guardando…':'Guardar visita'}</Text></Pressable></ScrollView>}
const s=StyleSheet.create({content:{padding:20,paddingBottom:40},center:{flex:1,justifyContent:'center',alignItems:'center',padding:25},h1:{fontSize:29,lineHeight:34,fontWeight:'900'},text:{fontSize:15,lineHeight:22,marginTop:8,marginBottom:18},label:{fontSize:15,fontWeight:'900',marginBottom:9},item:{padding:14,borderRadius:14,borderWidth:1,marginBottom:8},photoActions:{flexDirection:'row',gap:9},photoBtn:{flex:1,borderWidth:1,padding:13,borderRadius:14,alignItems:'center',gap:5},photo:{width:'100%',height:220,borderRadius:18,marginTop:12},input:{minHeight:105,textAlignVertical:'top',borderRadius:16,borderWidth:1,padding:14,marginTop:16,fontSize:15},btn:{marginTop:14,padding:16,borderRadius:16,alignItems:'center'},btnText:{color:'white',fontWeight:'900'}});
