import { useCallback, useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { Ionicons } from '@react-native-vector-icons/ionicons';
import { Evento } from '@/src/tipos';
import { obtenerEventos } from '@/src/servicios/eventos';
import { estaEventoGuardado, guardarEvento, quitarEvento } from '@/src/servicios/eventosGuardados';
import { useSesion } from '@/src/contexto/SesionContext';
import { useTema } from '@/src/contexto/TemaContext';
import { fechaEvento, pesos } from '@/src/utilidades/formato';
import { EstadoContenido } from '@/src/componentes/EstadoContenido';
import { NetworkBanner } from '@/src/componentes/NetworkBanner';
export default function Agenda(){const{colores}=useTema();const{usuario}=useSesion();const[eventos,setEventos]=useState<Evento[]>([]);const[guardados,setGuardados]=useState<Record<string,boolean>>({});const[cargando,setCargando]=useState(true);const[error,setError]=useState('');
 const cargar=async()=>{setCargando(true);setError('');const r=await obtenerEventos();if('error'in r){setError(r.error.mensaje);setCargando(false);return;}setEventos(r.datos);if(usuario){const pares=await Promise.all(r.datos.map(async e=>[e.id,await estaEventoGuardado(usuario.id,e.id)] as const));setGuardados(Object.fromEntries(pares));}else setGuardados({});setCargando(false)};
 useEffect(()=>{cargar()},[usuario?.id]);useFocusEffect(useCallback(()=>{if(usuario)cargar();},[usuario?.id]));
 const toggle=async(e:Evento)=>{if(!usuario){router.push('/(tabs)/cuenta');return;}try{if(guardados[e.id]){await quitarEvento(usuario.id,e.id);setGuardados(x=>({...x,[e.id]:false}));}else{await guardarEvento(usuario.id,e);setGuardados(x=>({...x,[e.id]:true}));Alert.alert('Evento guardado','Se programó un recordatorio antes del inicio.');}}catch(err){Alert.alert('No se pudo guardar',err instanceof Error?err.message:'Error inesperado')}};
 return <View style={[s.root,{backgroundColor:colores.fondo}]}><NetworkBanner/><ScrollView contentContainerStyle={s.content}><Text style={[s.kicker,{color:colores.primario}]}>AGENDA</Text><Text style={[s.h1,{color:colores.tinta}]}>Qué hacer en Colón</Text><Text style={[s.bajada,{color:colores.secundario}]}>Eventos por día, empezando por los próximos.</Text>{cargando?<EstadoContenido tipo="cargando"/>:error?<EstadoContenido tipo="error" mensaje={error} onReintentar={cargar}/>:eventos.length===0?<EstadoContenido tipo="vacio"/>:eventos.map(e=><Pressable key={e.id} onPress={()=>router.push({pathname:'/evento/[id]',params:{id:e.id}})} style={[s.card,{backgroundColor:colores.superficie,borderColor:colores.borde}]}>{e.imagenUrl?<Image source={{uri:e.imagenUrl}} style={s.image}/>:null}<View style={s.cardBody}><View style={s.row}><Text style={[s.fecha,{color:colores.primario}]}>{fechaEvento(e.inicio)}</Text><Text style={[s.estado,{color:e.estado==='programado'?colores.exito:colores.peligro}]}>{e.estado}</Text></View><Text style={[s.title,{color:colores.tinta}]}>{e.titulo}</Text><Text style={[s.desc,{color:colores.secundario}]} numberOfLines={2}>{e.descripcion}</Text><View style={[s.row,{marginTop:12}]}><Text style={[s.price,{color:colores.tinta}]}>{pesos(e.precio)}</Text><Pressable onPress={(ev)=>{ev.stopPropagation();toggle(e)}} style={[s.save,{backgroundColor:guardados[e.id]?colores.primario:colores.primarioSuave}]}><Ionicons name={guardados[e.id]?'bookmark':'bookmark-outline'} size={17} color={guardados[e.id]?'white':colores.primario}/><Text style={{color:guardados[e.id]?'white':colores.primario,fontWeight:'900',fontSize:12}}>{guardados[e.id]?'Guardado':'Guardar'}</Text></Pressable></View></View></Pressable>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1},content:{padding:20,paddingTop:58,paddingBottom:30},kicker:{fontSize:11,letterSpacing:1.4,fontWeight:'900'},h1:{fontSize:32,fontWeight:'900',marginTop:8},bajada:{fontSize:15,marginTop:8,marginBottom:20},card:{borderRadius:20,borderWidth:1,overflow:'hidden',marginBottom:14},image:{width:'100%',height:145},cardBody:{padding:17},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},fecha:{fontWeight:'900',fontSize:13,textTransform:'capitalize'},estado:{fontSize:11,fontWeight:'900',textTransform:'uppercase'},title:{fontSize:20,fontWeight:'900',marginTop:6},desc:{lineHeight:21,marginTop:6},price:{fontWeight:'900'},save:{paddingHorizontal:12,paddingVertical:9,borderRadius:12,flexDirection:'row',alignItems:'center',gap:5}});
