import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import Ionicons from '@react-native-vector-icons/ionicons';
import { useSesion } from '@/src/contexto/SesionContext';
import { useTema } from '@/src/contexto/TemaContext';
import { actualizarPreferencias } from '@/src/servicios/preferencias';
export default function Cuenta(){const{colores,modo,setModo}=useTema();const{usuario,sesionGuardada,bloqueada,cargando,login,registrar,logout,desbloquear,actualizarUsuario}=useSesion();const[modoForm,setModoForm]=useState<'login'|'registro'>('login');const[nombre,setNombre]=useState('');const[email,setEmail]=useState('lucia@mail.com');const[password,setPassword]=useState('123456');const[procesando,setProcesando]=useState(false);
 useEffect(()=>{if(usuario&&usuario.preferencias.tema!==modo)setModo(usuario.preferencias.tema)},[usuario?.id]);
 const enviar=async()=>{setProcesando(true);const r=modoForm==='login'?await login(email,password):await registrar(nombre,email,password);setProcesando(false);if(!r.ok)Alert.alert('No se pudo ingresar',r.mensaje)};
 const unlock=async()=>{const r=await desbloquear();if(!r.ok)Alert.alert('Biometría',r.mensaje)};
 const pref=async(cambios:any)=>{if(!usuario)return;const u=await actualizarPreferencias(usuario,cambios);await actualizarUsuario(u);if(cambios.tema)await setModo(cambios.tema)};
 if(cargando)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Text style={{color:colores.secundario}}>Cargando sesión…</Text></View>;
 if(bloqueada&&sesionGuardada)return <View style={[s.center,{backgroundColor:colores.fondo}]}><Ionicons name="finger-print" size={50} color={colores.primario}/><Text style={[s.big,{color:colores.tinta}]}>Reingreso seguro</Text><Text style={[s.centerText,{color:colores.secundario}]}>Tu sesión sigue guardada. Validá con huella o rostro para abrir tus datos personales.</Text><Pressable style={[s.btn,{backgroundColor:colores.primario}]} onPress={unlock}><Text style={s.btnText}>Usar biometría</Text></Pressable><Text style={[s.help,{color:colores.secundario}]}>Si tu dispositivo no tiene biometría, cerrá sesión y volvé a ingresar con email y contraseña.</Text><Pressable onPress={logout}><Text style={{color:colores.peligro,fontWeight:'900',marginTop:15}}>Usar contraseña</Text></Pressable></View>;
 if(!usuario)return <ScrollView style={{flex:1,backgroundColor:colores.fondo}} contentContainerStyle={s.content}><Text style={[s.kicker,{color:colores.primario}]}>TU CUENTA</Text><Text style={[s.h1,{color:colores.tinta}]}>Guardá tu viaje.</Text><Text style={[s.desc,{color:colores.secundario}]}>No hace falta una cuenta para explorar. Ingresá sólo si querés conservar favoritos, eventos y recorrido.</Text><View style={[s.tabs,{backgroundColor:colores.superficie2}]}><Pressable style={[s.tab,modoForm==='login'&&{backgroundColor:colores.superficie}]} onPress={()=>setModoForm('login')}><Text style={{color:colores.tinta,fontWeight:'900'}}>Ingresar</Text></Pressable><Pressable style={[s.tab,modoForm==='registro'&&{backgroundColor:colores.superficie}]} onPress={()=>setModoForm('registro')}><Text style={{color:colores.tinta,fontWeight:'900'}}>Registrarme</Text></Pressable></View>{modoForm==='registro'?<TextInput value={nombre} onChangeText={setNombre} placeholder="Nombre" placeholderTextColor={colores.secundario} style={[s.input,{color:colores.tinta,backgroundColor:colores.superficie,borderColor:colores.borde}]}/>:null}<TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={colores.secundario} style={[s.input,{color:colores.tinta,backgroundColor:colores.superficie,borderColor:colores.borde}]}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Contraseña" placeholderTextColor={colores.secundario} style={[s.input,{color:colores.tinta,backgroundColor:colores.superficie,borderColor:colores.borde}]}/><Pressable disabled={procesando} style={[s.btn,{backgroundColor:colores.primario,opacity:procesando?0.7:1}]} onPress={enviar}><Text style={s.btnText}>{procesando?'Procesando…':modoForm==='login'?'Ingresar':'Crear cuenta'}</Text></Pressable><Text style={[s.demo,{color:colores.secundario}]}>Para la demo con mocks podés usar lucia@mail.com / 123456.</Text></ScrollView>;
 const p=usuario.preferencias;return <ScrollView style={{flex:1,backgroundColor:colores.fondo}} contentContainerStyle={s.content}><Text style={[s.kicker,{color:colores.primario}]}>TU CUENTA</Text><Text style={[s.h1,{color:colores.tinta}]}>Hola, {usuario.nombre.split(' ')[0]}.</Text><Text style={[s.desc,{color:colores.secundario}]}>{usuario.email}</Text><View style={[s.card,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><Pressable style={s.row} onPress={()=>router.push('/favoritos')}><View style={s.rowLeft}><Ionicons name="star-outline" size={22} color={colores.primario}/><Text style={[s.rowText,{color:colores.tinta}]}>Mis favoritos</Text></View><Ionicons name="chevron-forward" size={18} color={colores.secundario}/></Pressable></View><Text style={[s.section,{color:colores.tinta}]}>Preferencias</Text><View style={[s.card,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><View style={s.row}><View style={s.rowLeft}><Ionicons name="notifications-outline" size={22} color={colores.primario}/><View><Text style={[s.rowText,{color:colores.tinta}]}>Avisos por proximidad</Text><Text style={{color:colores.secundario,fontSize:12}}>Máximo un aviso por lugar y día</Text></View></View><Switch value={p.avisarProximidad} onValueChange={v=>pref({avisarProximidad:v})}/></View><View style={[s.separator,{backgroundColor:colores.borde}]}/><Text style={[s.label,{color:colores.secundario}]}>Radio de aviso</Text><View style={s.options}>{([100,250,500] as const).map(v=><Pressable key={v} onPress={()=>pref({radioAvisoMetros:v})} style={[s.option,{backgroundColor:p.radioAvisoMetros===v?colores.primario:colores.superficie2}]}><Text style={{color:p.radioAvisoMetros===v?'white':colores.tinta,fontWeight:'900'}}>{v} m</Text></Pressable>)}</View><View style={[s.separator,{backgroundColor:colores.borde}]}/><Text style={[s.label,{color:colores.secundario}]}>Tema</Text><View style={s.options}>{(['claro','oscuro','sistema'] as const).map(v=><Pressable key={v} onPress={()=>pref({tema:v})} style={[s.option,{backgroundColor:p.tema===v?colores.primario:colores.superficie2}]}><Text style={{color:p.tema===v?'white':colores.tinta,fontWeight:'900',textTransform:'capitalize'}}>{v}</Text></Pressable>)}</View></View><Pressable onPress={logout} style={[s.logout,{borderColor:colores.peligro}]}><Ionicons name="log-out-outline" size={20} color={colores.peligro}/><Text style={{color:colores.peligro,fontWeight:'900'}}>Cerrar sesión</Text></Pressable></ScrollView>}
const s=StyleSheet.create({content:{padding:20,paddingTop:58,paddingBottom:36},center:{flex:1,alignItems:'center',justifyContent:'center',padding:28},centerText:{textAlign:'center',fontSize:15,lineHeight:22,marginVertical:10},big:{fontSize:27,fontWeight:'900',marginTop:12},help:{fontSize:12,textAlign:'center',lineHeight:18,marginTop:10},kicker:{fontSize:11,letterSpacing:1.4,fontWeight:'900'},h1:{fontSize:32,fontWeight:'900',marginTop:8},desc:{fontSize:15,lineHeight:22,marginTop:8,marginBottom:20},tabs:{flexDirection:'row',padding:4,borderRadius:14,marginBottom:14},tab:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:11},input:{height:54,borderRadius:16,borderWidth:1,paddingHorizontal:15,fontSize:16,marginBottom:10},btn:{paddingHorizontal:18,paddingVertical:15,borderRadius:15,alignItems:'center',marginTop:4},btnText:{color:'white',fontWeight:'900'},demo:{fontSize:12,lineHeight:18,textAlign:'center',marginTop:14},card:{borderRadius:19,borderWidth:1,padding:15,marginBottom:18},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},rowLeft:{flexDirection:'row',alignItems:'center',gap:10,flex:1},rowText:{fontSize:16,fontWeight:'900'},section:{fontSize:18,fontWeight:'900',marginBottom:10},separator:{height:1,marginVertical:15},label:{fontSize:12,fontWeight:'800',marginBottom:9},options:{flexDirection:'row',gap:8,flexWrap:'wrap'},option:{paddingHorizontal:13,paddingVertical:9,borderRadius:12},logout:{borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7}});
