import { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Location from 'expo-location';
import Ionicons from '@react-native-vector-icons/ionicons';
import { LugarCard } from '@/src/componentes/LugarCard';
import { NetworkBanner } from '@/src/componentes/NetworkBanner';
import { EstadoContenido } from '@/src/componentes/EstadoContenido';
import { obtenerCategorias, obtenerLugares } from '@/src/servicios/lugares';
import { Categoria, Coordenadas, Lugar } from '@/src/tipos';
import { distanciaKm, formatearDistancia } from '@/src/utilidades/distancia';
import { useTema } from '@/src/contexto/TemaContext';
export default function Inicio(){const{colores}=useTema();const[lugares,setLugares]=useState<Lugar[]>([]);const[categorias,setCategorias]=useState<Categoria[]>([]);const[categoria,setCategoria]=useState('todas');const[buscar,setBuscar]=useState('');const[ubicacion,setUbicacion]=useState<Coordenadas|null>(null);const[cargando,setCargando]=useState(true);const[error,setError]=useState('');
 const cargar=async()=>{setCargando(true);setError('');try{const[l,c]=await Promise.all([obtenerLugares(),obtenerCategorias()]);if('error'in l)throw new Error(l.error.mensaje);if('error'in c)throw new Error(c.error.mensaje);setLugares(l.datos);setCategorias(c.datos);const p=await Location.requestForegroundPermissionsAsync();if(p.granted){const u=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setUbicacion({latitud:u.coords.latitude,longitud:u.coords.longitude});}}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.');}finally{setCargando(false)}};
 useEffect(()=>{cargar()},[]);
 const visibles=useMemo(()=>lugares.filter(l=>(categoria==='todas'||l.categoriaId===categoria)&&(l.nombre+' '+l.descripcionCorta).toLowerCase().includes(buscar.trim().toLowerCase())).sort((a,b)=>ubicacion?distanciaKm(ubicacion,a.coordenadas)-distanciaKm(ubicacion,b.coordenadas):a.nombre.localeCompare(b.nombre)),[lugares,categoria,buscar,ubicacion]);
 return <View style={[s.root,{backgroundColor:colores.fondo}]}><NetworkBanner/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={[s.kicker,{color:colores.primario}]}>GUÍA TURÍSTICA · COLÓN</Text><Text style={[s.h1,{color:colores.tinta}]}>Descubrí qué tenés cerca.</Text><Text style={[s.bajada,{color:colores.secundario}]}>Lugares, patrimonio, naturaleza y agenda para recorrer la ciudad a tu ritmo.</Text><View style={[s.searchWrap,{backgroundColor:colores.superficie,borderColor:colores.borde}]}><Ionicons name="search-outline" size={20} color={colores.secundario}/><TextInput value={buscar} onChangeText={setBuscar} placeholder="Buscar por nombre…" placeholderTextColor={colores.secundario} style={[s.search,{color:colores.tinta}]} accessibilityLabel="Buscar lugar"/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><Pressable onPress={()=>setCategoria('todas')} style={[s.chip,{backgroundColor:categoria==='todas'?colores.primario:colores.superficie,borderColor:categoria==='todas'?colores.primario:colores.borde}]}><Text style={{fontWeight:'800',color:categoria==='todas'?'white':colores.tinta}}>Todos</Text></Pressable>{categorias.map(c=><Pressable key={c.id} onPress={()=>setCategoria(c.id)} style={[s.chip,{backgroundColor:categoria===c.id?colores.primario:colores.superficie,borderColor:categoria===c.id?colores.primario:colores.borde}]}><Text style={{fontWeight:'800',color:categoria===c.id?'white':colores.tinta}}>{c.nombre}</Text></Pressable>)}</ScrollView><View style={s.section}><Text style={[s.h2,{color:colores.tinta}]}>{ubicacion?'Cerca tuyo':'Lugares para explorar'}</Text><Text style={{color:colores.secundario,fontSize:12}}>{visibles.length} resultados</Text></View>{cargando?<EstadoContenido tipo="cargando"/>:error?<EstadoContenido tipo="error" mensaje={error} onReintentar={cargar}/>:visibles.length===0?<EstadoContenido tipo="vacio" mensaje="No encontramos lugares con ese filtro."/>:visibles.map(l=><LugarCard key={l.id} lugar={l} distancia={ubicacion?formatearDistancia(distanciaKm(ubicacion,l.coordenadas)):undefined}/>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1},content:{padding:20,paddingTop:58,paddingBottom:30},kicker:{fontSize:11,letterSpacing:1.4,fontWeight:'900'},h1:{fontSize:36,lineHeight:41,fontWeight:'900',marginTop:8},bajada:{fontSize:16,lineHeight:23,marginTop:10,marginBottom:20},searchWrap:{height:54,borderRadius:18,borderWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:15,gap:9},search:{flex:1,fontSize:16},chips:{gap:8,paddingVertical:16},chip:{paddingHorizontal:14,paddingVertical:10,borderRadius:999,borderWidth:1},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline',marginTop:6,marginBottom:12},h2:{fontSize:22,fontWeight:'900'}});
