import { useCallback, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import Ionicons from '@react-native-vector-icons/ionicons';
import { useSesion } from '@/src/contexto/SesionContext';
import { useTema } from '@/src/contexto/TemaContext';
import { obtenerRecorrido, sincronizarVisitasPendientes } from '@/src/servicios/visitas';
import { obtenerLugares } from '@/src/servicios/lugares';
import { Lugar, Visita } from '@/src/tipos';
import { fechaCorta } from '@/src/utilidades/formato';
import { EstadoContenido } from '@/src/componentes/EstadoContenido';
import { NetworkBanner } from '@/src/componentes/NetworkBanner';
export default function Recorrido(){const{colores}=useTema();const{usuario,bloqueada,sesionGuardada}=useSesion();const[visitas,setVisitas]=useState<Visita[]>([]);const[lugares,setLugares]=useState<Lugar[]>([]);const[cargando,setCargando]=useState(true);const[sinc,setSinc]=useState(false);
 const cargar=async()=>{if(!usuario){setCargando(false);return;}setCargando(true);const[v,l]=await Promise.all([obtenerRecorrido(usuario.id),obtenerLugares()]);setVisitas(v);if('datos'in l)setLugares(l.datos);setCargando(false)};
 useFocusEffect(useCallback(()=>{cargar()},[usuario?.id]));const nombre=(id:string)=>lugares.find(l=>l.id===id)?.nombre??id;const sync=async()=>{setSinc(true);await sincronizarVisitasPendientes();await cargar();setSinc(false)};
 if(!usuario)return <View style={[s.auth,{backgroundColor:colores.fondo}]}><Ionicons name="lock-closed-outline" size={38} color={colores.primario}/><Text style={[s.authTitle,{color:colores.tinta}]}>{bloqueada&&sesionGuardada?'Desbloqueá tu cuenta':'Ingresá para guardar tu recorrido'}</Text><Text style={[s.authText,{color:colores.secundario}]}>El mapa y los lugares son públicos. La cuenta se usa sólo para guardar visitas, fotos y favoritos.</Text><Pressable style={[s.primary,{backgroundColor:colores.primario}]} onPress={()=>router.push('/(tabs)/cuenta')}><Text style={s.primaryText}>Ir a mi cuenta</Text></Pressable></View>;
 return <View style={[s.root,{backgroundColor:colores.fondo}]}><NetworkBanner/><ScrollView contentContainerStyle={s.content}><Text style={[s.kicker,{color:colores.primario}]}>MI RECORRIDO</Text><Text style={[s.h1,{color:colores.tinta}]}>Tu viaje, guardado.</Text><Text style={[s.bajada,{color:colores.secundario}]}>Registrá visitas por QR, cercanía GPS o manualmente. Las pendientes se sincronizan cuando vuelve Internet.</Text><View style={s.actions}><Pressable style={[s.action,{backgroundColor:colores.primario}]} onPress={()=>router.push('/escanear')}><Ionicons name="qr-code-outline" size={22} color="white"/><Text style={s.primaryText}>QR</Text></Pressable><Pressable style={[s.action,{backgroundColor:colores.superficie,borderColor:colores.borde,borderWidth:1}]} onPress={()=>router.push({pathname:'/registrar-visita',params:{origen:'gps'}})}><Ionicons name="location-outline" size={22} color={colores.primario}/><Text style={{color:colores.tinta,fontWeight:'900'}}>GPS</Text></Pressable><Pressable style={[s.action,{backgroundColor:colores.superficie,borderColor:colores.borde,borderWidth:1}]} onPress={()=>router.push({pathname:'/registrar-visita',params:{origen:'manual'}})}><Ionicons name="create-outline" size={22} color={colores.primario}/><Text style={{color:colores.tinta,fontWeight:'900'}}>Manual</Text></Pressable></View><Pressable disabled={sinc} onPress={sync} style={s.syncButton}><Ionicons name="sync-outline" size={18} color={colores.primario}/><Text style={{color:colores.primario,fontWeight:'900'}}>{sinc?'Sincronizando…':'Sincronizar pendientes'}</Text></Pressable>{cargando?<EstadoContenido tipo="cargando"/>:visitas.length===0?<EstadoContenido tipo="vacio" mensaje="Todavía no registraste visitas."/>:visitas.map(v=><View key={v.id} style={[s.card,{backgroundColor:colores.superficie,borderColor:colores.borde}]}>{v.fotoUri?<Image source={{uri:v.fotoUri}} style={s.photo}/>:null}<View style={s.cardBody}><View style={s.top}><Text style={[s.title,{color:colores.tinta}]}>{nombre(v.lugarId)}</Text><Ionicons name={v.sincronizada?'cloud-done-outline':'cloud-offline-outline'} size={19} color={v.sincronizada?colores.exito:colores.advertencia}/></View><Text style={[s.meta,{color:colores.secundario}]}>{fechaCorta(v.fechaHora)} · {v.origen.toUpperCase()}</Text>{v.nota?<Text style={[s.note,{color:colores.tinta}]}>{v.nota}</Text>:null}<Text style={{fontSize:11,color:v.sincronizada?colores.exito:colores.advertencia,fontWeight:'800',marginTop:8}}>{v.sincronizada?'Sincronizada':'Guardada en el teléfono'}</Text></View></View>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1},content:{padding:20,paddingTop:58,paddingBottom:30},auth:{flex:1,justifyContent:'center',alignItems:'center',padding:28},authTitle:{fontSize:24,fontWeight:'900',textAlign:'center',marginTop:14},authText:{fontSize:15,lineHeight:22,textAlign:'center',marginTop:8,marginBottom:20},primary:{paddingHorizontal:18,paddingVertical:14,borderRadius:15},primaryText:{color:'white',fontWeight:'900'},kicker:{fontSize:11,letterSpacing:1.4,fontWeight:'900'},h1:{fontSize:32,fontWeight:'900',marginTop:8},bajada:{fontSize:15,lineHeight:22,marginTop:8},actions:{flexDirection:'row',gap:9,marginTop:18},action:{flex:1,paddingVertical:14,borderRadius:16,alignItems:'center',justifyContent:'center',gap:5},syncButton:{flexDirection:'row',alignItems:'center',gap:6,alignSelf:'flex-end',paddingVertical:13},card:{borderWidth:1,borderRadius:19,overflow:'hidden',marginBottom:12},photo:{width:'100%',height:170},cardBody:{padding:16},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},title:{fontSize:18,fontWeight:'900',flex:1},meta:{fontSize:12,marginTop:4},note:{marginTop:9,lineHeight:20}});
